### ISSUE TITLE
Make storing passwords more secure or change the security mentions in README to better reflect how secure the app is

### ISSUE THREAD

**Issue by evangelosmeklis** [PeepDB-dev/peepdb#20]
"I would not consider your passwords secure at all. It doesn’t matter how strong your encryption is if you don’t manage your keys securely. Don’t advertise this as “secure.”" 

Research needs to be done, either to make the keys storing more secure or changing for now the mentions regarding security

**Comment by evangelosmeklis** [comment]
I changed the README, but I'll leave this open in case more security features can be added in the future

**Comment by hasija** [comment]
Hey,
I am new to opensource, I think, i can help with this one.

The cause of concern is with the storage of "Fernet key"

we can avoid storage all together by generating the same dynamically with a salt and password.
And, we can inform users to store the credentials on thier side instead of storing it locally (maybe in a .env).
Also, giving an option to fetch the same through a .env or giving a promt to input the same.


Let me know if the below approach works, if so, then, i can pick this one. 😅 

Ref: [https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet](https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet)

**Comment by Aherontas** [comment]
Hello Hasija,

From my side makes sense to do that. One thing to add is that we probably should have an option to allow users to choose between inputting their password each time or using a stored method. For example, for users who prefer not to enter their password every time, suggest using secure storage solutions like OS-specific keyrings or encrypted files.

**Comment by hasija** [comment]
Yes, 

I could store the Fernet key as value in the keychain using the python keychain lib.
This would go with the current implementation and, then we could add an option to specify password for dynamic generation of fernet key as well.

Does this sound good?

Ref: [https://github.com/jaraco/keyring](url)

**Comment by evangelosmeklis** [comment]
@hasija yes do go ahead, remember to run the unittests before opening a PR and also add unittests for anything new you add to the main code
